### PR TITLE
Makes swagger-gen strictNull-able :)

### LINKED ISSUE #88: Generated code does not compile when using TypeScript's strictNullChecks
The generated code does not compile with the strictNull Flag of the typescript compiler.

### PR DESCRIPTION
**Pull request by aersamkull**
Fixes #88
In addition it replaces the void type by the "null" Type which seems to be more correct to me as angular will be using null for an empty body.

### CODE REVIEW

**Comment by aersamkull** [comment]
I tested this on a fairly large project that includes empty responses. So it should definitely work

**Comment by luisfpg** [comment]
Thanks for the PR. I'll be on vacations next week, and have plenty of things to finish before.
Will look at it when possible.

**Comment by luisfpg** [comment]
Thanks again for the PR.
I ended up not merging it.
The fix commit is heavily inspired by your solution, but I made it simpler and already took the opportunity to simplify a bit the operation generation. Besides, if an operation had a multipart upload, the generated code didn't compile.
Can you, please, try the commit https://github.com/cyclosproject/ng-swagger-gen/commit/2b22a108f8317c14053ffcdf95d367725f8a0349 to see if everything is working?

**Comment by luisfpg** [comment]
Actually, I've published the 1.3.0 version which includes this fix.
Please, test it and feel free to reopen the previous issue, or to report a new one.
Thanks again!

**Comment by aersamkull** [comment]
image
It does work quite good, however TypeScript does not get the correct type after the filter method. The simpliest fix would be using a cast: 
```
return this.http.request<any>(req).pipe(
      __filter(_r => _r instanceof HttpResponse),
      __map((_r) => {
        {{#operationIsVoid}}return (_r as HttpResponse<any>).clone({ body: null }) as {{{operationHttpResponseType}}}{{/operationIsVoid
        }}{{#operationIsNumber}}return (_r as HttpResponse<any>).clone({ body: parseFloat((_r as HttpResponse<any>).body as string) }) as {{{operationHttpResponseType}}}{{/operationIsNumber
        }}{{#operationIsBoolean}}return (_r as HttpResponse<any>).clone({ body: (_r as HttpResponse<any>).body === 'true' }) as {{{operationHttpResponseType}}}{{/operationIsBoolean
        }}{{#operationIsOther}}return _r as {{{operationHttpResponseType}}};{{/operationIsOther}}
      })
    );
```

**Pull request closed without merging**
