### PR TITLE
[Feat] Allow template options model overrides

### PR DESCRIPTION
**Pull request by gund**
Hi, first of all thanks for such a great tool!

I’ve been using it for quite some time and it is great and pretty flexible with mustache templates.

However, when I was trying to reduce generated boilerplate code for services (I have a lot of micro services) I hit a limitation.

## Problem

Basically I was trying to provide default configuration (rootUrl) at generation time, so I can avoid unnecessary config providers in my module imports.

And to do that I had to somehow supply `rootUrl` option for `configuration` template model.

## Solution

So I came up with pretty generic way of providing custom options for different template models straight from the JSON config files:

```jsonc
{
  "swagger": "…",
  // ...Normal config here...
  "templateOverrides": {
    // Every key here is the template name (eg: service, module, etc.)
    "configuration": {
      // Every key here is the name of prop in the model of template
      "rootUrl": "/api-foo-bar"
    }
  }
}
```

It’s working pretty good and also quite generic so you can do all sorts of customisations with it.

Also it’s completely optional - which mean no breaking changes required to upgrade.
It is simply on opt-in feature - use it if you need it.

I’ve published package with this feature available under my user scope - anyone can try in out: https://www.npmjs.com/package/@gund/ng-swagger-gen

Please let me know if this feature makes sense for you and if you have some comments/suggestions to it.

Thanks =)

### CODE REVIEW

**Comment by luisfpg** [comment]
First, thanks for the PR.
Sorry, but such extensions (in this case `templateOverrides`) is allowed by the [swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields), and, hence, I don't see it being handled by the generator.
This also couples the swagger description file to `ng-swagger-gen`, which is not desirable.
So, I'm not merging it, as I'd say it's out of scope for the generator.

**Comment by gund** [comment]
Hi, thanks for reply.

But I’m not sure that you understood the use case.

I know that in swagger you can specify `basePath` but it is the path on backend side.

What I’m trying to achieve is provide path on frontend side.
Very often APIs are proxied to frontend applications via paths like `/api/` or `/api-user/` etc.
And this information is irrelevant to swagger docs - because it is up to every client how they consume APIs.

So this feature is simply to remove the unnecessary step of providing configuration at runtime via `.forRoot()` methods where you usually provide `rootPath` and instead being able to provide it directly during codegen step.

**Comment by luisfpg** [comment]
Hi @gund. I understend the use case.
But why polluting the swagger spec with ng-swagger-gen's specific settings?
I see it harder than providing a static rootUrl in forRoot...

**Comment by gund** [comment]
I do not really understand what do you mean by "polluting swagger spec".

What I'm talking about has nothing to do with swagger neither it's specs.
It is only concerning the generation - which is this library's specific settings.

I want to be able to get rid from necessity of providing the configurations to the generated modules:

**Before:**

For every generated service you had to specify config like so:
```ts
@NgModule({
  imports: [
    GeneratedApiModule.forRoot({rootUrl: '/my-api'}), // <-- This line is always required right now
  ]
})
export class MyModule {}
```

**After:**

```ts
@NgModule({
  imports: [
    // <-- Look ma, no need to even import the generated module!
    // Because it already was generated with that `/my-api` rootUrl, how cool is that?
  ]
})
export class MyModule {}
```

I guess now it's more clear what exactly I mean and why has nothing to do with swagger whatsoever.

**Comment by luisfpg** [comment]
Hi @gund. I think you got my point, as you've closed the PR.
Just to clarify: the rootUrl needs to be specified somewhere: either in `Module.forRoot` (or by injecting the configuration and setting it) or in the swagger descriptor (yaml / json).
In the latter there's the extra downside of putting there things which are out of the Swagger specification and only works for ng-swagger-gen...

**Comment by gund** [comment]
Actually I did not close PR =)

And secondly, as you just said, "the rootUrl needs to be specified somewhere" which is exactly my point - why should we force user to specify it always?

With this feature we eliminate extra configuration at runtime (by not requiring `Module.forRoot`) which reduces configuration boilerplate, amount of code that requires support and also better treeshaking (because `Module.forRoot` will require you to import statement, and without - it will not be included in the application).

Again just to clarify - this feature has nothing to do with swagger, it's specs nor external services that you want to consume.
It is purely application's concern as to which path to use for generated services and so it is this library's concern to allow to provide it - and doing it at generation time instead of runtime is just more optimal way of doing this.

Anyways I'm really sorry to be so annoying - I just wanted to make sure my point of view is clear.
If you really do not see benefit of this feature - I will understand.

Thanks

**Pull request closed without merging**
