### PR TITLE
Generating examples for the models from their respective `example` sections.

### PR DESCRIPTION
**Pull request by ganqqwerty**
The mocks are used for the unit tests, which partially addresses #58

### CODE REVIEW

**Comment by luisfpg** [comment]
I'm overloaded with work in the next days, so I'll probably take a deeper look only next week.
From a quick look, I have 3 points:

- I'm just not sure that 'mock' is the correct name for model examples. Mocks are generally stub implementations of a service / class. In this case, they are really examples of a data model.
Would it be possible to just do a case-sensitive search / replace in files for `Mock` -> `Example` and `mock` -> `example`?
- I see some comments in Russian (I think). Can you, please, translate them to English?
- Finally, I think the examples generation should be customizable via the configuration file. For that, you would need to add a setting, such as `generateExamples` in the configuration file / JSON schema / README.md. Can you add those?

Thanks for the PR!

**Comment by ganqqwerty** [comment]
* yes, absolutely, I will fix all the points you mentioned

**Comment by ganqqwerty** [comment]
all done, please check now

**Comment by ganqqwerty** [comment]
yes, you're right, I need to skip them

**Comment by ganqqwerty** [comment]
done!

**Comment by luisfpg** [comment]
Merged.
Will be published on 1.1.0.
Thanks!

**Comment by ganqqwerty** [comment]
thanks to you too! Now when I got all those jsons generated, I start to realize that they're not that practical. 
It turned out to be super-weird to load them and assign a proper TS type to them. I guess it will be much more practical to generate ts files instead.

**Comment by luisfpg** [comment]
:(
I agree that it would be easier to use `.ts` files directly.
For that, I would say:

- The generated examples should be in a separated directory, such as `src/app/api/examples`
- The example file name could be `model-example.ts`
- Each example should be something like:
```typescript
import { Model } from '../models/model';
const example: Model = {
  "property": "value"
};
export default example;
```

Then, to use, one would just do something like:
```typescript
import modelExample from 'app/api/examples/model-example';

// Use modelExample directly
```

What do you think? Can you do it?

**Comment by ganqqwerty** [comment]
I think it makes sense. I will try to implement it

**Comment by ganqqwerty** [comment]
I think it would be better to place the examples right besides the models, actually, because when you look at the project tree, it will be easier to see which models have examples, and which don't. Please check out my implementation.

**Pull request merged**
